/**
 * Line Chart Schema
 * Property definitions for the Line Chart component
 */

import type { ComponentSchema } from "@/components/bi/schema-types";

export const linechartSchema: ComponentSchema = {
  componentType: "line-chart",
  displayName: "Line Chart",
  icon: "LineChart",
  category: "Charts",
  description: "Time series visualization for displaying trends over time",
  properties: [
    {
      key: "title",
      type: "string",
      label: "Title",
      defaultValue: "",
      controlType: "input",
      placeholder: "Chart title",
      category: "General",
    },
    {
      key: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
      controlType: "textarea",
      placeholder: "Chart description",
      category: "General",
    },
    {
      key: "data",
      hidden: true,
      type: "array",
      label: "Data",
      description: "Array of data points",
      defaultValue: [],
      controlType: "array-builder",
      category: "Data",
    },
    {
      key: "xKey",
      type: "string",
      label: "X-Axis Field",
      description: "Field name for X-axis values (string or date columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select X-axis column",
      category: "Data",
      isDataField: true,
      dataFieldType: "x-axis",
      allowedColumnTypes: ["string", "date"],
      validation: { required: true },
    },
    {
      key: "yKeys",
      type: "array",
      label: "Y-Axis Fields",
      description: "Field names for Y-axis values (numeric columns, supports multiple lines)",
      defaultValue: [],
      controlType: "array-builder",
      validation: { minItems: 1, required: true },
      category: "Data",
      isDataField: true,
      dataFieldType: "y-axis",
      allowedColumnTypes: ["number"],
    },
    {
      key: "color",
      type: "color",
      label: "Primary Line Color",
      description: "Primary line color (additional lines use default palette)",
      defaultValue: "var(--chart-1)",
      controlType: "color-picker",
      category: "Appearance",
    },
    {
      key: "showGrid",
      type: "boolean",
      label: "Show Grid",
      description: "Display grid lines",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
    {
      key: "showLegend",
      type: "boolean",
      label: "Show Legend",
      description: "Display chart legend",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
    {
      key: "curve",
      type: "enum",
      label: "Line Curve",
      description: "Line interpolation style",
      defaultValue: "monotone",
      controlType: "select",
      options: [
        { value: "monotone", label: "Smooth (Monotone)" },
        { value: "linear", label: "Linear" },
        { value: "step", label: "Step" },
        { value: "basis", label: "Basis" },
      ],
      category: "Appearance",
    },
  ],
};
