/**
 * Advanced Component Schemas
 * Property definitions for advanced visualization components
 */

import type { ComponentSchema } from "../types";

export const advancedSchemas: ComponentSchema[] = [
    {
        componentType: "waterfall-chart",
        displayName: "Waterfall Chart",
        icon: "BarChart3",
        category: "Advanced",
        description: "Visualize cumulative effect of positive and negative values",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "labelKey",
                type: "string",
                label: "Label Field",
                description: "Field for category labels",
                defaultValue: "label",
                controlType: "input",
            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                description: "Field for values",
                defaultValue: "value",
                controlType: "input",
            },
            {
                key: "showTotal",
                type: "boolean",
                label: "Show Total",
                description: "Display total bar at the end",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "heatmap",
        displayName: "Heatmap",
        icon: "Grid3x3",
        category: "Advanced",
        description: "Display data density with color intensity",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "x",
                controlType: "input",
            },
            {
                key: "yKey",
                type: "string",
                label: "Y-Axis Field",
                defaultValue: "y",
                controlType: "input",
            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                description: "Field for heat intensity",
                defaultValue: "value",
                controlType: "input",
            },
            {
                key: "colorScale",
                type: "enum",
                label: "Color Scale",
                defaultValue: "blues",
                controlType: "select",
                options: [
                    { value: "blues", label: "Blues" },
                    { value: "greens", label: "Greens" },
                    { value: "reds", label: "Reds" },
                    { value: "oranges", label: "Oranges" },
                    { value: "purples", label: "Purples" },
                ],
            },
        ],
    },

    {
        componentType: "treemap",
        displayName: "TreeMap",
        icon: "LayoutGrid",
        category: "Advanced",
        description: "Hierarchical data visualization with nested rectangles",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "nameKey",
                type: "string",
                label: "Name Field",
                defaultValue: "name",
                controlType: "input",
            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                defaultValue: "value",
                controlType: "input",
            },
            {
                key: "showLabels",
                type: "boolean",
                label: "Show Labels",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "funnel-chart",
        displayName: "Funnel Chart",
        icon: "Filter",
        category: "Advanced",
        description: "Visualize stages in a process with decreasing values",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "nameKey",
                type: "string",
                label: "Stage Name Field",
                defaultValue: "name",
                controlType: "input",
            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                defaultValue: "value",
                controlType: "input",
            },
            {
                key: "showPercentages",
                type: "boolean",
                label: "Show Percentages",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "bullet-chart",
        displayName: "Bullet Chart",
        icon: "Gauge",
        category: "Advanced",
        description: "Compare actual vs target with context zones",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "label",
                type: "string",
                label: "Label",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "value",
                type: "number",
                label: "Current Value",
                defaultValue: 0,
                controlType: "number",
            },
            {
                key: "target",
                type: "number",
                label: "Target Value",
                defaultValue: 100,
                controlType: "number",
            },
            {
                key: "max",
                type: "number",
                label: "Maximum",
                defaultValue: 100,
                controlType: "number",
            },
        ],
    },

    {
        componentType: "sankey-diagram",
        displayName: "Sankey Diagram",
        icon: "GitBranch",
        category: "Advanced",
        description: "Flow diagram showing quantity distribution",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "showValues",
                type: "boolean",
                label: "Show Flow Values",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "matrix",
        displayName: "Matrix",
        icon: "Table",
        category: "Advanced",
        description: "Grid-based data matrix",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "rowKey",
                type: "string",
                label: "Row Field",
                defaultValue: "row",
                controlType: "input",
            },
            {
                key: "colKey",
                type: "string",
                label: "Column Field",
                defaultValue: "col",
                controlType: "input",
            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                defaultValue: "value",
                controlType: "input",
            },
        ],
    },

    {
        componentType: "forecast-line",
        displayName: "Forecast Line",
        icon: "TrendingUp",
        category: "Advanced",
        description: "Line chart with forecasted values",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "month",
                controlType: "input",
            },
            {
                key: "yKey",
                type: "string",
                label: "Y-Axis Field",
                defaultValue: "value",
                controlType: "input",
            },
            {
                key: "showConfidenceInterval",
                type: "boolean",
                label: "Show Confidence Interval",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "anomaly-badge",
        displayName: "Anomaly Badge",
        icon: "AlertTriangle",
        category: "Advanced",
        description: "Highlight anomalies with severity indicator",
        properties: [
            {
                key: "label",
                type: "string",
                label: "Label",
                defaultValue: "Anomaly Detected",
                controlType: "input",
            },
            {
                key: "severity",
                type: "enum",
                label: "Severity",
                defaultValue: "medium",
                controlType: "select",
                options: [
                    { value: "low", label: "Low" },
                    { value: "medium", label: "Medium" },
                    { value: "high", label: "High" },
                ],
            },
        ],
    },
];
