/**
 * Scatter Chart Schema
 * Property definitions for the Scatter Chart component
 */

import type { ComponentSchema } from "@/components/bi/schema-types";

export const scatterchartSchema: ComponentSchema = {
  componentType: "scatter-chart",
  displayName: "Scatter Chart",
  icon: "Circle",
  category: "Charts",
  description: "Correlation visualization with data points",
  properties: [
    {
      key: "title",
      type: "string",
      label: "Title",
      defaultValue: "",
      controlType: "input",
      placeholder: "Chart title",
      category: "General",
    },
    {
      key: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
      controlType: "textarea",
      placeholder: "Chart description",
      category: "General",
    },
    {
      key: "data",
      hidden: true,
      type: "array",
      label: "Data",
      defaultValue: [],
      controlType: "array-builder",
      category: "Data",
    },
    {
      key: "xKey",
      type: "string",
      label: "X-Axis Field",
      description: "Field name for X-axis values (numeric columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select X-axis column",
      category: "Data",
      isDataField: true,
      dataFieldType: "x-axis",
      allowedColumnTypes: ["number"],
      validation: { required: true },
    },
    {
      key: "yKey",
      type: "string",
      label: "Y-Axis Field",
      description: "Field name for Y-axis values (numeric columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select Y-axis column",
      category: "Data",
      isDataField: true,
      dataFieldType: "y-axis",
      allowedColumnTypes: ["number"],
      validation: { required: true },
    },
    {
      key: "nameKey",
      type: "string",
      label: "Name Field (Optional)",
      description: "Field for point labels (string columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select name column",
      category: "Data",
      isDataField: true,
      dataFieldType: "name",
      allowedColumnTypes: ["string"],
    },
    {
      key: "sizeKey",
      type: "string",
      label: "Size Field (Optional)",
      description: "Field for bubble sizes (numeric columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select size column",
      category: "Data",
      isDataField: true,
      dataFieldType: "value",
      allowedColumnTypes: ["number"],
    },
    {
      key: "showGrid",
      type: "boolean",
      label: "Show Grid",
      description: "Display grid lines",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
  ],
};
