/**
 * Area Chart Schema
 * Property definitions for the Area Chart component
 */

import type { ComponentSchema } from "@/components/bi/schema-types";

export const areachartSchema: ComponentSchema = {
  componentType: "area-chart",
  displayName: "Area Chart",
  icon: "AreaChart",
  category: "Charts",
  description: "Cumulative trends with filled areas",
  properties: [
    {
      key: "title",
      type: "string",
      label: "Title",
      defaultValue: "",
      controlType: "input",
      placeholder: "Chart title",
      category: "General",
    },
    {
      key: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
      controlType: "textarea",
      placeholder: "Chart description",
      category: "General",
    },
    {
      key: "data",
      hidden: true,
      type: "array",
      label: "Data",
      defaultValue: [],
      controlType: "array-builder",
      category: "Data",
    },
    {
      key: "xKey",
      type: "string",
      label: "X-Axis Field",
      description: "Field name for X-axis values (string or date columns)",
      defaultValue: "",
      controlType: "input",
      placeholder: "Select X-axis column",
      category: "Data",
      isDataField: true,
      dataFieldType: "x-axis",
      allowedColumnTypes: ["string", "date"],
      validation: { required: true },
    },
    {
      key: "yKeys",
      type: "array",
      label: "Y-Axis Fields",
      description: "Field names for Y-axis values (numeric columns)",
      defaultValue: [],
      controlType: "array-builder",
      validation: { minItems: 1, required: true },
      category: "Data",
      isDataField: true,
      dataFieldType: "y-axis",
      allowedColumnTypes: ["number"],
    },
    {
      key: "stacked",
      type: "boolean",
      label: "Stacked Areas",
      description: "Stack areas on top of each other",
      defaultValue: false,
      controlType: "toggle",
      category: "Appearance",
    },
    {
      key: "gradient",
      type: "boolean",
      label: "Use Gradient",
      description: "Apply gradient fill",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
    {
      key: "fillOpacity",
      type: "number",
      label: "Fill Opacity",
      description: "Area fill opacity (0-1)",
      defaultValue: 0.3,
      controlType: "slider",
      validation: { min: 0, max: 1 },
      category: "Appearance",
    },
    {
      key: "showGrid",
      type: "boolean",
      label: "Show Grid",
      description: "Display grid lines",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
    {
      key: "showLegend",
      type: "boolean",
      label: "Show Legend",
      description: "Display chart legend",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
  ],
};
