/**
 * Charts Component Schemas
 * Property definitions for all chart components
 */

import type { ComponentSchema } from "../types";

export const chartSchemas: ComponentSchema[] = [
    {
        componentType: "line-chart",
        displayName: "Line Chart",
        icon: "LineChart",
        category: "Charts",
        description: "Time series visualization for displaying trends over time",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
                placeholder: "Chart title",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
                placeholder: "Chart description",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                description: "Array of data points",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                description: "Field name for X-axis values",
                defaultValue: "",
                controlType: "input",

                placeholder: "e.g., month, date, category",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                description: "Field names for Y-axis values (supports multiple lines)",
                defaultValue: [],
                controlType: "array-builder",
                validation: { minItems: 1 },
            },
            {
                key: "color",
                type: "color",
                label: "Line Color",
                description: "Primary line color",
                defaultValue: "#8884d8",
                controlType: "color-picker",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                description: "Display grid lines",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                description: "Display chart legend",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "curve",
                type: "enum",
                label: "Line Curve",
                description: "Line interpolation style",
                defaultValue: "monotone",
                controlType: "select",
                options: [
                    { value: "monotone", label: "Smooth (Monotone)" },
                    { value: "linear", label: "Linear" },
                    { value: "step", label: "Step" },
                    { value: "basis", label: "Basis" },
                ],
            },
        ],
    },

    {
        componentType: "bar-chart",
        displayName: "Bar Chart",
        icon: "BarChart3",
        category: "Charts",
        description: "Comparison view for categorical data",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "description",
                type: "string",
                label: "Description",
                defaultValue: "",
                controlType: "textarea",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
                validation: { minItems: 1 },
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
                validation: { minItems: 1 },
            },
            {
                key: "stacked",
                type: "boolean",
                label: "Stacked Bars",
                description: "Stack bars on top of each other",
                defaultValue: false,
                controlType: "toggle",
            },
            {
                key: "horizontal",
                type: "boolean",
                label: "Horizontal Orientation",
                description: "Display bars horizontally",
                defaultValue: false,
                controlType: "toggle",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "area-chart",
        displayName: "Area Chart",
        icon: "AreaChart",
        category: "Charts",
        description: "Cumulative trends with filled areas",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "stacked",
                type: "boolean",
                label: "Stacked Areas",
                defaultValue: false,
                controlType: "toggle",
            },
            {
                key: "gradient",
                type: "boolean",
                label: "Use Gradient",
                description: "Apply gradient fill",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "fillOpacity",
                type: "number",
                label: "Fill Opacity",
                description: "Area fill opacity (0-1)",
                defaultValue: 0.3,
                controlType: "slider",
                validation: { min: 0, max: 1 },
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "pie-chart",
        displayName: "Pie Chart",
        icon: "PieChart",
        category: "Charts",
        description: "Part-to-whole visualization",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "nameKey",
                type: "string",
                label: "Name Field",
                description: "Field for segment labels",
                defaultValue: "name",
                controlType: "input",

            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                description: "Field for segment values",
                defaultValue: "value",
                controlType: "input",

            },
            {
                key: "innerRadius",
                type: "number",
                label: "Inner Radius",
                description: "Inner radius for donut effect (0-100)",
                defaultValue: 0,
                controlType: "slider",
                validation: { min: 0, max: 100 },
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "donut-chart",
        displayName: "Donut Chart",
        icon: "CircleDot",
        category: "Charts",
        description: "Donut-style pie chart",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "nameKey",
                type: "string",
                label: "Name Field",
                defaultValue: "name",
                controlType: "input",

            },
            {
                key: "valueKey",
                type: "string",
                label: "Value Field",
                defaultValue: "value",
                controlType: "input",

            },
            {
                key: "innerRadius",
                type: "number",
                label: "Inner Radius",
                defaultValue: 60,
                controlType: "slider",
                validation: { min: 30, max: 90 },
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "scatter-chart",
        displayName: "Scatter Chart",
        icon: "Circle",
        category: "Charts",
        description: "Correlation visualization with data points",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "yKey",
                type: "string",
                label: "Y-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "sizeKey",
                type: "string",
                label: "Size Field (Optional)",
                description: "Field for bubble sizes",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "stacked-bar-chart",
        displayName: "Stacked Bar Chart",
        icon: "BarChart4",
        category: "Charts",
        description: "Stacked horizontal bars",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
                validation: { minItems: 1 },
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "stacked-column-chart",
        displayName: "Stacked Column Chart",
        icon: "BarChart2",
        category: "Charts",
        description: "Stacked vertical columns",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",

            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",

            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
                validation: { minItems: 1 },
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "stacked-area-chart",
        displayName: "Stacked Area Chart",
        icon: "AreaChart",
        category: "Charts",
        description: "Stacked area visualization",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "showLegend",
                type: "boolean",
                label: "Show Legend",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "clustered-bar-chart",
        displayName: "Clustered Bar Chart",
        icon: "BarChart",
        category: "Charts",
        description: "Grouped bars for comparison",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "clustered-column-chart",
        displayName: "Clustered Column Chart",
        icon: "BarChart3",
        category: "Charts",
        description: "Grouped columns for comparison",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "showGrid",
                type: "boolean",
                label: "Show Grid",
                defaultValue: true,
                controlType: "toggle",
            },
        ],
    },

    {
        componentType: "line-stacked-column-chart",
        displayName: "Line & Stacked Column",
        icon: "TrendingUp",
        category: "Charts",
        description: "Combo chart with line and stacked columns",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Column Fields",
                description: "Fields for stacked columns",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "lineKeys",
                type: "array",
                label: "Line Fields",
                description: "Fields for line series",
                defaultValue: [],
                controlType: "array-builder",
            },
        ],
    },

    {
        componentType: "ribbon-chart",
        displayName: "Ribbon Chart",
        icon: "Waves",
        category: "Charts",
        description: "Streamgraph visualization",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "xKey",
                type: "string",
                label: "X-Axis Field",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "yKeys",
                type: "array",
                label: "Y-Axis Fields",
                defaultValue: [],
                controlType: "array-builder",
            },
        ],
    },

    {
        componentType: "radar-chart",
        displayName: "Radar Chart",
        icon: "Radar",
        category: "Charts",
        description: "Multi-dimensional data visualization",
        properties: [
            {
                key: "title",
                type: "string",
                label: "Title",
                defaultValue: "",
                controlType: "input",
            },
            {
                key: "data",
                hidden: true,
                type: "array",
                label: "Data",
                defaultValue: [],
                controlType: "array-builder",
            },
            {
                key: "categoryKey",
                type: "string",
                label: "Category Field",
                description: "Field for radar axes",
                defaultValue: "category",
                controlType: "input",
            },
            {
                key: "valueKeys",
                type: "array",
                label: "Value Fields",
                description: "Data series fields",
                defaultValue: [],
                controlType: "array-builder",
            },
        ],
    },
];
