/**
 * Pie Chart Schema
 * Property definitions for the Pie Chart component
 */

import type { ComponentSchema } from "@/components/bi/schema-types";

export const piechartSchema: ComponentSchema = {
  componentType: "pie-chart",
  displayName: "Pie Chart",
  icon: "PieChart",
  category: "Charts",
  description: "Part-to-whole visualization",
  properties: [
    {
      key: "title",
      type: "string",
      label: "Title",
      defaultValue: "",
      controlType: "input",
      placeholder: "Chart title",
      category: "General",
    },
    {
      key: "description",
      type: "string",
      label: "Description",
      defaultValue: "",
      controlType: "textarea",
      placeholder: "Chart description",
      category: "General",
    },
    {
      key: "data",
      hidden: true,
      type: "array",
      label: "Data",
      defaultValue: [],
      controlType: "array-builder",
      category: "Data",
    },
    {
      key: "nameKey",
      type: "string",
      label: "Name Field",
      description: "Field for segment labels (string columns)",
      defaultValue: "name",
      controlType: "input",
      placeholder: "Select name column",
      category: "Data",
      isDataField: true,
      dataFieldType: "name",
      allowedColumnTypes: ["string"],
      validation: { required: true },
    },
    {
      key: "valueKey",
      type: "string",
      label: "Value Field",
      description: "Field for segment values (numeric columns)",
      defaultValue: "value",
      controlType: "input",
      placeholder: "Select value column",
      category: "Data",
      isDataField: true,
      dataFieldType: "value",
      allowedColumnTypes: ["number"],
      validation: { required: true },
    },
    {
      key: "innerRadius",
      type: "number",
      label: "Inner Radius",
      description: "Inner radius for donut effect (0-100)",
      defaultValue: 0,
      controlType: "slider",
      validation: { min: 0, max: 100 },
      category: "Appearance",
    },
    {
      key: "showLegend",
      type: "boolean",
      label: "Show Legend",
      description: "Display chart legend",
      defaultValue: true,
      controlType: "toggle",
      category: "Appearance",
    },
  ],
};
